/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as NovelRouteImport } from './routes/novel'
import { Route as LabRouteImport } from './routes/lab'
import { Route as DevRouteImport } from './routes/dev'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWebsearchRouteImport } from './routes/api/websearch'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NovelRoute = NovelRouteImport.update({
  id: '/novel',
  path: '/novel',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebsearchRoute = ApiWebsearchRouteImport.update({
  id: '/api/websearch',
  path: '/api/websearch',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/dev': typeof DevRoute
  '/lab': typeof LabRoute
  '/novel': typeof NovelRoute
  '/settings': typeof SettingsRoute
  '/api/websearch': typeof ApiWebsearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/dev': typeof DevRoute
  '/lab': typeof LabRoute
  '/novel': typeof NovelRoute
  '/settings': typeof SettingsRoute
  '/api/websearch': typeof ApiWebsearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/dev': typeof DevRoute
  '/lab': typeof LabRoute
  '/novel': typeof NovelRoute
  '/settings': typeof SettingsRoute
  '/api/websearch': typeof ApiWebsearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/dev'
    | '/lab'
    | '/novel'
    | '/settings'
    | '/api/websearch'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/dev'
    | '/lab'
    | '/novel'
    | '/settings'
    | '/api/websearch'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/dev'
    | '/lab'
    | '/novel'
    | '/settings'
    | '/api/websearch'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  DevRoute: typeof DevRoute
  LabRoute: typeof LabRoute
  NovelRoute: typeof NovelRoute
  SettingsRoute: typeof SettingsRoute
  ApiWebsearchRoute: typeof ApiWebsearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novel': {
      id: '/novel'
      path: '/novel'
      fullPath: '/novel'
      preLoaderRoute: typeof NovelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/websearch': {
      id: '/api/websearch'
      path: '/api/websearch'
      fullPath: '/api/websearch'
      preLoaderRoute: typeof ApiWebsearchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  DevRoute: DevRoute,
  LabRoute: LabRoute,
  NovelRoute: NovelRoute,
  SettingsRoute: SettingsRoute,
  ApiWebsearchRoute: ApiWebsearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
